import type { Metadata } from "next";
import { Xanh_Mono, Plus_Jakarta_Sans, Gasoek_One } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Sidebar from "@/components/layout/sidebar";

const xanhMono = Xanh_Mono({
  variable: "--font-xanh-mono",
  weight: "400",
  subsets: ["latin"],
});

const gasoekOne = Gasoek_One({
  variable: "--font-gasoek-one",
  weight: "400",
  subsets: ["latin"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // metadataBase ensures canonical/OG URLs generated by Next are absolute in production.
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000"),
  title: {
    default: "Travel Blog",
    template: "%s | Travel Blog",
  },
  description:
    "Stories and photos of long walks, wrong turns, and everyday discoveries",
  openGraph: {
    title: "Travel Blog",
    description:
      "Stories and photos of long walks, wrong turns, and everyday discoveries",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${xanhMono.variable} ${gasoekOne.variable} ${plusJakartaSans.variable} antialiased min-w-80 font-jakarta`}
      >
        <div className="w-full relative overflow-clip">
          {/* Skip link improves keyboard navigation and is a common a11y baseline. */}
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only focus:fixed focus:top-3 focus:left-3 focus:z-1000 focus:bg-background focus:text-foreground focus:px-4 focus:py-2 focus:rounded-full"
          >
            Skip to main content
          </a>
          <Header />
          <div className="lg:flex">
            <Sidebar />
            <main id="main-content" className="lg:flex-1 relative z-99">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
